version: '3.8'

services:
  traveseros:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_SERVICE_NAME}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - traveseros

  db:
    image: postgres:13
    container_name: ${DB_SERVICE_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
